name: Online Status Monitor
on:
  schedule:
    - cron: '*/5 * * * *'  # A cada 5 minutos
  workflow_dispatch:

jobs:
  check-status:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Necessário para commitar mudanças
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Verificar Status
        id: status
        run: |
          # Método simplificado (substitua pelo seu verificador real)
          ping -c 1 google.com > /dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "STATUS=Online" >> $GITHUB_OUTPUT
            echo "🟢 ONLINE" > status.txt
          else
            echo "STATUS=Offline" >> $GITHUB_OUTPUT
            echo "🔴 OFFLINE" > status.txt
          fi
          
      - name: Commit Status
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update status: ${{ steps.status.outputs.STATUS }}"
          file_pattern: status.txt
